run:
  timeout: 5m
  skip-files:
    - "zz_generated.*\\.go$"
    - ".*conversion.*\\.go$"
  allow-parallel-runners: true

linters:
  enable:
    - bodyclose
    - durationcheck
    - exportloopref
    - forcetypeassert
    - gofmt
    - gocritic
    - makezero
    - nilerr
    - paralleltest
    - thelper
    - promlinter
    - asciicheck
    - depguard
    - errorlint
    - gosec
    - importas
    - prealloc
    - revive
    - stylecheck
    - tparallel
    - unconvert
    - unparam
    - errcheck
    - goconst
    - govet
    - godot
    - typecheck
    - varcheck
  fast: false

linters-settings:
  depguard:
    include-go-root: true
    packages:
      - sync/atomic
    packages-with-error-message:
      - sync/atomic: "please use type-safe atomics from go.uber.org/atomic"
  errcheck:
    check-type-assertions: true
    check-blank: true
  exhaustive:
    check-generated: true
    default-signifies-exhaustive: false
  gocritic:
    enabled-tags:
      - performance
      - diagnostic
      - opinionated
      - style
      - experimental
    disabled-checks:
      - commentedOutCode
      - whyNoLint
      - hugeParam
      - unnamedResult
  importas:
    no-unaliased: true
    alias:
      # Kubernetes
      - pkg: k8s.io/api/core/v1
        alias: corev1
      - pkg: k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1
        alias: apiextensionsv1
      - pkg: k8s.io/apimachinery/pkg/apis/meta/v1
        alias: metav1
      - pkg: k8s.io/apimachinery/pkg/api/errors
        alias: apierrors
      - pkg: k8s.io/apimachinery/pkg/util/errors
        alias: kerrors
      # Controller Runtime
      - pkg: sigs.k8s.io/controller-runtime
        alias: ctrl
  staticcheck:
    # Select the Go version to target. The default is '1.13'.
    go: "1.16"
    # https://staticcheck.io/docs/options#checks
    checks: [ "all" ]
  stylecheck:
    go: "1.16"

issues:
  exclude-use-default: false
  exclude-rules:
    - linters:
        - revive
      text: exported (method|function|type|const|var) (.+) should have comment
    - linters:
        - errcheck
      text: Error return value of (.+\.Sync.+) is not checked
    - linters:
        - revive
      text: package-comments
    - linters:
        - stylecheck
      text: "ST1000:"
    # Append should be able to assign to a different var/slice.
    - linters:
        - gocritic
      text: "appendAssign: append result not assigned to the same slice"
    - linters:
        - gocritic
      text: "singleCaseSwitch: should rewrite switch statement to if statement"
  exclude:
    - "ST1000: at least one file in a package should have a package comment"
