# Make sure to check the documentation at http://goreleaser.com
env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
builds:
  - ldflags:
      - -s -w -X github.com/aerfio/gobc/internal/version.version={{.Version}} -X github.com/aerfio/gobc/internal/version.commit={{.ShortCommit}} -X github.com/aerfio/gobc/internal/version.date={{.Date}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64

archives:
  - format: binary

checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
release:
  prerelease: auto
  name_template: "v{g{.Version}}"
