# Make sure to check the documentation at http://goreleaser.com
env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
    - go mod download
builds:
  - ldflags:
      - -s -w -X github.com/aerfio/gobc/internal/version.commit={{.Version}} -X github.com/aerfio/gobc/internal/version.commit={{.ShortCommit}} -X github.com/aerfio/gobc/internal/version.date={{.Date}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows

archives:
  - format: binary
    replacements:
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
release:
  prerelease: auto
  name_template: "{{.ProjectName}}-v{{.Version}}"
