# This is a basic workflow to help you get started with Actions

name: CICD

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # The "build" workflow
  test-build-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16' # The Go version to download (if necessary) and use.
      - name: Test and build
        run: |
          go test -race ./...
          go build .
      - name: Lint
        run: |
          make setup
          make lint
